**Задача 1.** Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):  
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],  
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].  
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy  
Полученные значения должны быть равны.  
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков, а затем с использованием функций из библиотек numpy и pandas. 

In [1]:
import numpy as np
from scipy import stats

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

np.cov(zp,ks,ddof = 0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [3]:
cov = np.mean(zp*ks) - np.mean(zp)*np.mean(ks)
cov

9157.839999999997

In [4]:
np.corrcoef(zp,ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [5]:
np.cov(zp,ks,ddof = 0)/(np.std(zp,ddof = 0)*np.std(ks,ddof = 0))

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

**Задача 2.** Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:  
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.  
Известно, что в генеральной совокупности IQ распределен нормально.  
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [6]:
a = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

avg = np.mean(a)
d = np.var(a, ddof=1)
t = stats.t.ppf(0.975, 9)

x1 = avg - t*np.sqrt(d/10)
x2 = avg + t*np.sqrt(d/10)
print(f'Доверительный интервал для среднего: [{round(x1, 2)}, {round(x2, 2)}]')

Доверительный интервал для среднего: [110.56, 125.64]


**Задача 3.** Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [7]:
a1 = 174.2 - (1.96*5/np.sqrt(27))
a2 = 174.2 + (1.96*5/np.sqrt(27))
print(f'Доверительный интервал для среднего: [{round(a1,2)}, {round(a2,2)}]')

Доверительный интервал для среднего: [172.31, 176.09]
